export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"


export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST"
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS"
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL"


export const GET_DATA_PRODUCT_VERIFICATION_REQUEST = "GET_DATA_PRODUCT_VERIFICATION_REQUEST"
export const GET_DATA_PRODUCT_VERIFICATION_SUCCESS = "GET_DATA_PRODUCT_VERIFICATION_SUCCESS"
export const GET_DATA_PRODUCT_VERIFICATION_FAIL = "GET_DATA_PRODUCT_VERIFICATION_FAIL"


export const ADMIN_PRODUCT_CONTROL_METHOD_REQUEST = "ADMIN_PRODUCT_CONTROL_METHOD_REQUEST"
export const ADMIN_PRODUCT_CONTROL_METHOD_SUCCESS = "ADMIN_PRODUCT_CONTROL_METHOD_SUCCESS"
export const ADMIN_PRODUCT_CONTROL_METHOD_FAIL = "ADMIN_PRODUCT_CONTROL_METHOD_FAIL"


export const GET_ALL_REJECTED_PRODUCTS_REQUEST = "GET_ALL_REJECTED_PRODUCTS_REQUEST"
export const GET_ALL_REJECTED_PRODUCTS_SUCCESS = "GET_ALL_REJECTED_PRODUCTS_SUCCESS"
export const GET_ALL_REJECTED_PRODUCTS_FAIL = "GET_ALL_REJECTED_PRODUCTS_FAIL"


export const GET_ALL_VERIFIED_PRODUCTS_REQUEST = "GET_ALL_VERIFIED_PRODUCTS_REQUEST"
export const GET_ALL_VERIFIED_PRODUCTS_SUCCESS = "GET_ALL_VERIFIED_PRODUCTS_SUCCESS"
export const GET_ALL_VERIFIED_PRODUCTS_FAIL = "GET_ALL_VERIFIED_PRODUCTS_FAIL"


export const GET_REJECTED_PRODUCTS_OF_USER_REQUEST = "GET_REJECTED_PRODUCTS_OF_USER_REQUEST"
export const GET_REJECTED_PRODUCTS_OF_USER_SUCCESS = "GET_REJECTED_PRODUCTS_OF_USER_SUCCESS"
export const GET_REJECTED_PRODUCTS_OF_USER_FAIL = "GET_REJECTED_PRODUCTS_OF_USER_FAIL"


export const GET_PRODUCTS_USEWISE_REQUEST = "GET_REJECTED_PRODUCTS_OF_USER_REQUEST"
export const GET_PRODUCTS_USEWISE_SUCCESS = "GET_REJECTED_PRODUCTS_OF_USER_SUCCESS"
export const GET_PRODUCTS_USEWISE_FAIL = "GET_REJECTED_PRODUCTS_OF_USER_FAIL"


export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"


export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST"
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS"
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL"


export const REMOVE_CART_ITEMS_REQUEST = "REMOVE_CART_ITEMS_REQUEST"
export const REMOVE_CART_ITEMS_SUCCESS = "REMOVE_CART_ITEMS_SUCCESS"
export const REMOVE_CART_ITEMS_FAIL = "REMOVE_CART_ITEMS_FAIL"


export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"


export const CART_REMOVE_ORDERED_ITEMS_REQUEST = "CART_REMOVE_ORDERED_ITEMS_REQUEST"
export const CART_REMOVE_ORDERED_ITEMS_SUCCESS = "CART_REMOVE_ORDERED_ITEMS_SUCCESS"
export const CART_REMOVE_ORDERED_ITEMS_FAIL = "CART_REMOVE_ORDERED_ITEMS_FAIL"


export const GET_USER_ORDERED_ITEMS_REQUEST = "GET_USER_ORDERED_ITEMS_REQUEST"
export const GET_USER_ORDERED_ITEMS_SUCCESS = "GET_USER_ORDERED_ITEMS_SUCCESS"
export const GET_USER_ORDERED_ITEMS_FAIL = "GET_USER_ORDERED_ITEMS_FAIL"


export const GET_RECEIVED_ORDERS_REQUEST = "GET_RECEIVED_ORDERS_REQUEST"
export const GET_RECEIVED_ORDERS_SUCCESS = "GET_RECEIVED_ORDERS_SUCCESS"
export const GET_RECEIVED_ORDERS_FAIL = "GET_RECEIVED_ORDERS_FAIL"

export const EDIT_REJ_PRODUCT_REQUEST = "EDIT_REJ_PRODUCT_REQUEST"
export const EDIT_REJ_PRODUCT_SUCCESS = "EDIT_REJ_PRODUCT_SUCCESS"
export const EDIT_REJ_PRODUCT_FAIL = "EDIT_REJ_PRODUCT_FAIL"


export const DELETE_USER_PRODUCT_REQUEST = "DELETE_USER_PRODUCT_REQUEST"
export const DELETE_USER_PRODUCT_SUCCESS = "DELETE_USER_PRODUCT_SUCCESS"
export const DELETE_USER_PRODUCT_FAIL = "DELETE_USER_PRODUCT_FAIL"


export const GET_USER_PRODUCTS_REQUEST = "GET_USER_PRODUCTS_REQUEST"
export const GET_USER_PRODUCTS_SUCCESS = "GET_USER_PRODUCTS_SUCCESS"
export const GET_USER_PRODUCTS_FAIL = "GET_USER_PRODUCTS_FAIL"


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"


export const DESTROY_USER_PRODUCTS_REQUEST = "DESTROY_USER_PRODUCTS_REQUEST"
export const DESTROY_USER_PRODUCTS_SUCCESS = "DESTROY_USER_PRODUCTS_SUCCESS"
export const DESTROY_USER_PRODUCTS_FAIL = "DESTROY_USER_PRODUCTS_FAIL"

