export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"
export const CLOSE_TOAST = "CLOSE_TOAST"

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL"

export const DELETE_SIGNLE_USER_REQUEST = "DELETE_SIGNLE_USER_REQUEST"
export const DELETE_SIGNLE_USER_SUCCESS = "DELETE_SIGNLE_USER_SUCCESS"
export const DELETE_SIGNLE_USER_FAIL = "DELETE_SIGNLE_USER_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"

